# Generated by Django 4.1.3 on 2022-11-08 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Created_date',
            new_name='created_date',
        ),
    ]
