# Generated by Django 4.1.3 on 2022-11-09 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phone_numer',
            new_name='phone_numebr',
        ),
    ]
