# Generated by Django 4.1.3 on 2022-11-09 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_phone_numer_account_phone_numebr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phone_numebr',
            new_name='phone_number',
        ),
    ]
